apiVersion: v1
kind: Namespace
metadata:
  name: namespace1
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota1
  namespace: namespace1
spec:
  hard:
    cpu: "25"
    memory: "7Mi"
    pods: "15"
    replicationcontrollers: "20"
    resourcequotas: "1"
    services: "5"
