apiVersion: v1
kind: Namespace
metadata:
  name: namespace1
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace1-quota
  namespace: namespace1
spec:
  hard:
    requests
      cpu: "200m"  
    limits
      cpu: "300m"
