apiVersion: v1
kind: Namespace
metadata:
  name: namespace1
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota1
  namespace: namespace1
spec:
  hard:
    cpu: "20"
    memory: "6Mi"
    pods: "10"
    replicationcontrollers: "20"
    resourcequotas: "1"
    services: "5"
