apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-apache
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: namespace2
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.6.3
    chart: apache
  sources: []
  project: default
